#!/bin/sh
DIR=`dirname $0`

if [ -e $DIR/../deps/cpy/cpy ]; then
	CPY=$DIR/../deps/cpy/cpy
else
	CPY=$DIR/deps/cpy/cpy
fi

fc=$FAST_CPY
export FAST_CPY=yes
$CPY $DIR/ssdb-cli.cpy $@
export FAST_CPY=$fc
