#!/bin/sh
SCRIPT=`readlink -f "$0"`
[ -z "$SCRIPT" ] && SCRIPT=$0
DIR=`dirname $SCRIPT`


if [ -e $DIR/../deps/cpy/cpy ]; then
	CPY=$DIR/../deps/cpy/cpy
else
	CPY=$DIR/deps/cpy/cpy
fi

$CPY $DIR/ssdb-cli.cpy $@
